In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
from scipy.spatial import distance

In [2]:
from google.colab import files
uploaded = files.upload()

Saving int_online_tx.csv to int_online_tx.csv

In [3]:
df = pd.read_csv('/content/int_online_tx.csv')

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/10 8:45,3.75,12583.0,France
1,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/10 8:45,3.75,12583.0,France
2,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/10 8:45,3.75,12583.0,France
3,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,0.85,12583.0,France
4,536370,21883,STARS GIFT TAPE,24,12/1/10 8:45,0.65,12583.0,France

In [5]:
df.shape

(35116, 8)

In [6]:
df.isnull().sum()

InvoiceNo         0
StockCode         0
Description       0
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     1418
Country           0
dtype: int64

In [7]:
df['CustomerID']=df['CustomerID'].fillna(df['CustomerID'].mean())

In [8]:
dataset = pd.read_csv("int_online_tx.csv")

dataset = dataset[
    [
        "Quantity",
        "UnitPrice",
        "CustomerID"
    ]
]

# Remove missing values
dataset = dataset.dropna()

print(dataset.head())
print(dataset.shape)

k = 3

distanceType = "euclidean"

maxCols = dataset.shape[1]
maxRows = dataset.shape[0]

X = np.asarray(dataset)

iterations = 0
runFlag = True

random.seed(42)

medoidsPoints = random.sample(range(maxRows), k)

medoidsPointsEveryIterations = [medoidsPoints]

distanceMatrixEveryIter = []

clusterIndividual = []

S = []

   Quantity  UnitPrice  CustomerID
0        24       3.75     12583.0
1        24       3.75     12583.0
2        12       3.75     12583.0
3        12       0.85     12583.0
4        24       0.65     12583.0
(33698, 3)